### ISSUE TITLE
audiobookshelf crash when scanning local folder used by AntennaPod

### ISSUE THREAD

**Issue by arthurlutz** [advplyr/audiobookshelf-app#165]
### Steps to reproduce

1. Install AntennaPod & audiobookshelf-app
2. Download some podcasts
3. Add folder where podcasts are stored as Podcast, launch scan, get : 

```
FATAL EXCEPTION: CapacitorPlugins
Process: com.audiobookshelf.app, PID: 3662
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:601)
	at com.getcapacitor.Bridge$$ExternalSyntheticLambda5.run(D8$$SyntheticClass)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:121)
	at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:592)
	... 5 more
Caused by: com.fasterxml.jackson.module.kotlin.MissingKotlinParameterException: Instantiation of [simple type, class com.audiobookshelf.app.data.AudioProbeResult] value failed for JSON property streams due to missing (therefore NULL) value for creator parameter streams which is a non-nullable type
 at [Source: (String)"{

}
"; line: 3, column: 1] (through reference chain: com.audiobookshelf.app.data.AudioProbeResult["streams"])
	at com.fasterxml.jackson.module.kotlin.KotlinValueInstantiator.createFromObjectWith(KotlinValueInstantiator.kt:116)
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:202)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:520)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1390)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:362)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:195)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3548)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3531)
	at com.audiobookshelf.app.device.FolderScanner.probeAudioFile(FolderScanner.kt:500)
	at com.audiobookshelf.app.device.FolderScanner.scanLibraryItemFolder(FolderScanner.kt:152)
	at com.audiobookshelf.app.device.FolderScanner.scanForMediaItems(FolderScanner.kt:74)
	at com.audiobookshelf.app.plugins.AbsFileSystem.scanFolder(AbsFileSystem.kt:148)
	... 8 more
```

In my case I ended up with one episode added, and then the above traceback (collected with scoop) 

### Expected behaviour
- No crash

### Actual behaviour
- Crash

### Environment data

Audiobookshelf Version:  v0.9.43-beta 

- [x] Android App 
- [ ] iOS App?

#### Android Issue
Android version: 7.1.2

Device model: samsung htc m8

Stock or customized system: lineageos 14.1

**Comment by advplyr** [comment]
What is the format of the audio files that are getting scanned? The error here is showing that no streams were found on the media file when it was probed.

**Comment by arthurlutz** [comment]
```
file */* | cut -d':' -f2 | awk '{gsub(/^ +| +$/,"")} {print $0}' | sort | uniq
Audio file with ID3 version 2.3.0, contains
Audio file with ID3 version 2.4.0, contains
empty
ISO Media
MPEG ADTS, layer III, v1, 256 kbps, 44.1 kHz, JntStereo
MPEG ADTS, layer III, v1, 320 kbps, 44.1 kHz, JntStereo
```

**Comment by advplyr** [comment]
I have been seeing crash reports of this error from all types of devices and versions but I can't seem to reproduce it myself

**Comment by advplyr** [comment]
The latest release should no longer crash when this happens but the audio files won't be probed
