### ISSUE TITLE
[Enchantment]: In Book view, make author and series text as anchor point

### ISSUE THREAD

**Issue by superpawko** [advplyr/audiobookshelf-app#186]
In Book view, make author and series text as anchor point, so It would be easy to go from book to an author , and from book to a serie.

**Comment by kebbe** [comment]
Yes, please. Maybe add the same behavior for the now playing screen.

**Comment by hobesman** [comment]
+1 I came to post this same request but found this already listed.

**Comment by superpawko** [comment]
for 1200, 444 had somekind of error here is log from one: 

```
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the [add-ons section](https://forums.ankiweb.net/c/add-ons/11) of our support site. 
Debug info:
Anki 2.1.53 (96bacf79) Python 3.9.7 Qt 5.15.2 PyQt 5.15.5
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-06-03 13:20:56

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 42, in cmd
  File "aqt.webview", line 149, in _onCmd
  File "aqt.webview", line 619, in _onBridgeCmd
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 86, in repl
  File "C:\Users\Pawel\AppData\Roaming\Anki2\addons21\799647424\main.py", line 183, in on_bridge_cmd
    _old(editor, command)
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 86, in repl
  File "C:\Users\Pawel\AppData\Roaming\Anki2\addons21\24411424\custom_shortcuts.py", line 440, in cs_captureBridgeToggleSticky
    return _old(self,cmd)
  File "aqt.editor", line 467, in onBridgeCmd
  File "C:\Users\Pawel\AppData\Roaming\Anki2\addons21\124265771\audio_downloader.py", line 817, in button_pressed
    audio_files = get_ll_results(term)
  File "C:\Users\Pawel\AppData\Roaming\Anki2\addons21\124265771\audio_downloader.py", line 392, in get_ll_results
    audio_file_paths.extend(forvo_results[0])
IndexError: list index out of range
```

**Comment by advplyr** [comment]
Added in [v0.9.47-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.47-beta)
