### ISSUE TITLE
HarmonyOS 3.0.0  crash in splash screen

### ISSUE THREAD

**Issue by ilwzmf** [advplyr/audiobookshelf-app#480]
更新鸿蒙3.0.0之后，app闪退，安装多个版本都闪退
HarmonyOS 3.0.0, HUAWEI P40 Pro, v0.9.60-beta

**Comment by advplyr** [comment]
Is this still a problem? I don't have a way to test this.

**Comment by ilwzmf** [comment]
Yes, I setup Android Studio on Mac, throw Exception
I add "try catch" on initCastManager. It could be run normally.
![Snipaste_2023-02-27_10-24-36](https://user-images.githubusercontent.com/3972546/221459126-1c5c8a4c-8670-4fdb-b126-0cd48cacfb8f.png)


D/Capacitor: Registering plugin instance: AbsAudioPlayer
V/MediaRouter: Selecting route: RouteInfo{ name=手机, description=null, status=null, category=RouteCategory{ name=系统 types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
I/MediaRouter: Skip setBluetoothA2dpOn(): types=8388615, isPlaybackActive()=false, BT route=null
I/MediaRouter: Found default route: MediaRouter.RouteInfo{ uniqueId=android/androidx.mediarouter.media.SystemMediaRouteProvider:DEFAULT_ROUTE, name=手机, description=null, iconUri=null, enabled=true, connectionState=0, canDisconnect=false, playbackType=0, playbackStream=3, deviceType=0, volumeHandling=1, volume=3, volumeMax=15, presentationDisplayId=-1, extras=null, settingsIntent=null, providerPackageName=android }
I/MediaRouter: Unselecting the current route because it is no longer selectable: null
D/CastOptionsProvider: getCastOptions
I/StubController: system app validUid:10749, isFriend:true
W/System: ClassLoader referenced unknown path: /data/user_de/0/com.google.android.gms/app_chimera/m/0000001e/DynamiteLoader.apk
I/LoadedApk: makePaths: outLibPaths=[/data/app/~~Jw8KoMXm_3U0xGRv3kdJ7g==/com.google.android.gms-vOtVxE4ZaJtTTmtg3AF2kg==/lib/arm64, /data/app/~~Jw8KoMXm_3U0xGRv3kdJ7g==/com.google.android.gms-vOtVxE4ZaJtTTmtg3AF2kg==/base.apk!/lib/arm64-v8a, /data/app/~~Jw8KoMXm_3U0xGRv3kdJ7g==/com.google.android.gms-vOtVxE4ZaJtTTmtg3AF2kg==/split_config.xxxhdpi.apk!/lib/arm64-v8a, /data/app/~~Jw8KoMXm_3U0xGRv3kdJ7g==/com.google.android.gms-vOtVxE4ZaJtTTmtg3AF2kg==/split_config.zh.apk!/lib/arm64-v8a, /system/lib64:/hw_product/lib64:/system/lib64/module/multimedia:/system/product/lib64]
I/LoadedApk: createSharedLibrariesLoaders::sharedLibraries is [SharedLibraryInfo{name:org.apache.http.legacy, type:builtin, version:-1}, SharedLibraryInfo{name:com.android.media.remotedisplay, type:builtin, version:-1}, SharedLibraryInfo{name:com.android.location.provider, type:builtin, version:-1}]
I/LoadedApk: createSharedLibrariesLoaders::sharedLibraries is null
I/ApplicationLoaders: getSharedLibraryClassLoaderWithSharedLibraries::loader is null
I/LoadedApk: createSharedLibrariesLoaders::sharedLibraries is null
I/ApplicationLoaders: getSharedLibraryClassLoaderWithSharedLibraries::loader is null
I/LoadedApk: createSharedLibrariesLoaders::sharedLibraries is null
I/ApplicationLoaders: getSharedLibraryClassLoaderWithSharedLibraries::loader is null
I/DynamiteModule: Considering local module com.google.android.gms.cast.framework.dynamite:0 and remote module com.google.android.gms.cast.framework.dynamite:226
I/DynamiteModule: Selected remote version of com.google.android.gms.cast.framework.dynamite, version >= 226
I/LoadedApk: makePaths: outLibPaths=[/data/app/~~Jw8KoMXm_3U0xGRv3kdJ7g==/com.google.android.gms-vOtVxE4ZaJtTTmtg3AF2kg==/lib/arm64, /data/app/~~Jw8KoMXm_3U0xGRv3kdJ7g==/com.google.android.gms-vOtVxE4ZaJtTTmtg3AF2kg==/base.apk!/lib/arm64-v8a, /data/app/~~Jw8KoMXm_3U0xGRv3kdJ7g==/com.google.android.gms-vOtVxE4ZaJtTTmtg3AF2kg==/split_config.xxxhdpi.apk!/lib/arm64-v8a, /data/app/~~Jw8KoMXm_3U0xGRv3kdJ7g==/com.google.android.gms-vOtVxE4ZaJtTTmtg3AF2kg==/split_config.zh.apk!/lib/arm64-v8a, /system/lib64:/hw_product/lib64:/system/lib64/module/multimedia:/system/product/lib64]
W/System: ClassLoader referenced unknown path: 
W/System: ClassLoader referenced unknown path: /data/user_de/0/com.google.android.gms/app_chimera/m/00000020/DynamiteModulesC.apk
W/ChimeraFileApk: Failed to validate PathClassLoader for /data/user_de/0/com.google.android.gms/app_chimera/m/00000020/DynamiteModulesC.apk: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.chimera.DynamiteModuleInitializer" on path: DexPathList[[],nativeLibraryDirectories=[/data/user_de/0/com.google.android.gms/app_chimera/m/00000020/DynamiteModulesC.apk!/lib/arm64-v8a, /system/lib64, /hw_product/lib64, /system/lib64/module/multimedia, /system/product/lib64]]
E/ChimeraModuleLdr: Failed to load code for module FileApk(/data/user_de/0/com.google.android.gms/app_chimera/m/00000020/DynamiteModulesC.apk)
    gya: Can't load code for DynamiteModulesC.apk
        at gtk.g(:com.google.android.gms@230514044@23.05.14 (190400-509319212):8)
        at gxz.a(:com.google.android.gms@230514044@23.05.14 (190400-509319212):48)
        at gxz.b(:com.google.android.gms@230514044@23.05.14 (190400-509319212):4)
        at com.google.android.gms.dynamiteloader.DynamiteLoaderV2.loadModule2NoCrashUtils(:com.google.android.gms@230514044@23.05.14 (190400-509319212):50)
        at com.google.android.gms.chimera.container.DynamiteLoaderImpl.loadModule(:com.google.android.gms@230514044@23.05.14 (190400-509319212):4)
        at com.google.android.gms.chimera.container.DynamiteLoaderImpl.createModuleContext3NoCrashUtils(:com.google.android.gms@230514044@23.05.14 (190400-509319212):7)
        at afmv.eo(:com.google.android.gms@230514044@23.05.14 (190400-509319212):5)
        at gma.onTransact(:com.google.android.gms@230514044@23.05.14 (190400-509319212):12)
        at android.os.Binder.transact(Binder.java:1071)
        at com.google.android.gms.internal.common.zza.zzB(com.google.android.gms:play-services-basement@@18.0.0:2)
        at com.google.android.gms.dynamite.zzq.zzi(com.google.android.gms:play-services-basement@@18.0.0:6)
        at com.google.android.gms.dynamite.DynamiteModule.load(com.google.android.gms:play-services-basement@@18.0.0:21)
        at com.google.android.gms.internal.cast.zzm.zzf(com.google.android.gms:play-services-cast-framework@@20.1.0:2)
        at com.google.android.gms.internal.cast.zzm.zza(com.google.android.gms:play-services-cast-framework@@20.1.0:1)
        at com.google.android.gms.cast.framework.CastContext.<init>(com.google.android.gms:play-services-cast-framework@@20.1.0:4)
        at com.google.android.gms.cast.framework.CastContext.getSharedInstance(com.google.android.gms:play-services-cast-framework@@20.1.0:7)
        at com.audiobookshelf.app.player.CastManager.getContext(CastManager.kt:309)
        at com.audiobookshelf.app.player.CastManager.access$getContext(CastManager.kt:19)
        at com.audiobookshelf.app.player.CastManager$startRouteScan$callback$1.onRouteUpdate(CastManager.kt:128)
        at com.audiobookshelf.app.player.CastManager$ScanCallback.onFilteredRouteUpdate(CastManager.kt:246)
        at com.audiobookshelf.app.player.CastManager.startRouteScan(CastManager.kt:152)
        at com.audiobookshelf.app.plugins.AbsAudioPlayer.initCastManager(AbsAudioPlayer.kt:169)
        at com.audiobookshelf.app.plugins.AbsAudioPlayer.load(AbsAudioPlayer.kt:40)
        at com.getcapacitor.PluginHandle.loadInstance(PluginHandle.java:115)
        at com.getcapacitor.PluginHandle.load(PluginHandle.java:105)
        at com.getcapacitor.PluginHandle.<init>(PluginHandle.java:65)
        at com.getcapacitor.Bridge.registerPlugin(Bridge.java:627)
        at com.getcapacitor.Bridge.registerAllPlugins(Bridge.java:583)
        at com.getcapacitor.Bridge.<init>(Bridge.java:210)
        at com.getcapacitor.Bridge.<init>(Unknown Source:0)
        at com.getcapacitor.Bridge$Builder.create(Bridge.java:1502)
        at com.getcapacitor.BridgeActivity.load(BridgeActivity.java:43)
        at com.getcapacitor.BridgeActivity.onCreate(BridgeActivity.java:37)
        at com.audiobookshelf.app.MainActivity.onCreate(MainActivity.kt:61)
        at android.app.Activity.performCreate(Activity.java:8488)
        at android.app.Activity.performCreate(Activity.java:8461)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1343)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4602)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4842)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:113)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2928)
        at android.os.Handler.dispatchMessage(Handler.java:117)
        at android.os.Looper.loopOnce(Looper.java:205)
E/ChimeraModuleLdr:     at android.os.Looper.loop(Looper.java:293)
        at android.app.ActivityThread.main(ActivityThread.java:9596)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1204)

**Comment by advplyr** [comment]
Fixed in [v0.9.64-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.64-beta)
