### ISSUE TITLE
app crashes

### ISSUE THREAD

**Issue by zrwd01** [advplyr/audiobookshelf-app#843]
### Steps to reproduce

1.open the app

### Actual behaviour
- Tell us what happens
app crashes

### Environment data

Audiobookshelf Version:
v0.9.65-beta

Android App

#### Android Issue
Android version:
5.15.74-android13-8-00049-g8945ccdb2203-ab9500309

Device model:
redmi k60 pro

Stock or customized system:
MIUI

### Steps to reproduce

1.open the app

### Actual behaviour
- Tell us what happens
app crashes

### Environment data

Audiobookshelf Version:
v0.9.65-beta

Android App

#### Android Issue
Android version:
5.15.74-android13-8-00049-g8945ccdb2203-ab9500309

Device model:
redmi k60 pro

Stock or customized system:
MIUI

##error message

java.lang.OutOfMemoryError: Failed to allocate a 131447696 byte allocation with 100663296 free bytes and 108MB until OOM, target footprint 523418296, growth limit 536870912
	at java.lang.StringFactory.newStringFromChars(StringFactory.java:112)
	at java.lang.StringBuilder.toString(StringBuilder.java:413)
	at org.json.JSONStringer.toString(JSONStringer.java:443)
	at org.json.JSONObject.toString(JSONObject.java:703)
	at com.audiobookshelf.app.server.ApiHandler.postRequest(ApiHandler.kt:53)
	at com.audiobookshelf.app.server.ApiHandler.sendSyncLocalSessions(ApiHandler.kt:327)
	at com.audiobookshelf.app.plugins.AbsDatabase$syncLocalSessionsWithServer$1.invoke(AbsDatabase.kt:230)
	at com.audiobookshelf.app.plugins.AbsDatabase$syncLocalSessionsWithServer$1.invoke(AbsDatabase.kt:225)
	at com.audiobookshelf.app.server.ApiHandler$syncLocalMediaProgressForUser$1.invoke(ApiHandler.kt:381)
	at com.audiobookshelf.app.server.ApiHandler$syncLocalMediaProgressForUser$1.invoke(ApiHandler.kt:357)
	at com.audiobookshelf.app.server.ApiHandler$getCurrentUser$1.invoke(ApiHandler.kt:124)
	at com.audiobookshelf.app.server.ApiHandler$getCurrentUser$1.invoke(ApiHandler.kt:118)
	at com.audiobookshelf.app.server.ApiHandler$makeRequest$1.onResponse(ApiHandler.kt:104)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by oridark** [comment]
same problem, especially when the audiobook's size is too big, 10 GB or bigger

**Comment by lerndmina** [comment]
I'm getting some crashes. But I don't know if the cause is similar. It seems to happen when listening to downloaded books with lots of individual mp3 files.

**Comment by gazpachoking** [comment]
> I'm getting some crashes. But I don't know if the cause is similar. It seems to happen when listening to downloaded books with lots of individual mp3 files.

That sounds like it might be similar to what I'm having documented in #773

**Comment by advplyr** [comment]
The original issue here is saying the crash is happening when first opening the app, before playing anything.
Is this still happening on 0.9.66?

**Comment by zrwd01** [comment]
This has not happened since I switched to 0.9.66
